spring.application.name=gestao-api
server.port=8080

# H2 em arquivo ? dados persistem entre reinicializações
spring.datasource.url=jdbc:h2:file:./data/gestao_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA ? update mantém os dados existentes ao reiniciar
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Error tracing
server.error.include-message=always
server.error.include-stacktrace=always

# CORS
cors.allowed-origins=http://localhost:3000

# Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.show-actuator=false

jwt.validity=3600000
jwt.secret=RXhpc3R1IHVtYSBOZW9yaWEgcXV1IGRpeiBxdWUSIHNIIHVtIGRpYSBhbGd16W0gZGVzY291cmlyIGV4YXRhbWVudGUgcGFyYSBxdWUgc2VydmUgbyBVbm12ZXJzby